#!/usr/bin/env ruby

N = 4

(1..N).each do |id|
Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.define "node-#{id}" do |node|
    node.vm.hostname = "node-#{id}"
      node.vm.network "private_network", ip: "192.168.77.#{9+id}"
    node.vm.box = "generic/ubuntu2004"
    node.vm.provider "libvirt" do |v|
      v.memory = "1024"
      v.cpus = "1"
      end

    if id == N 
      node.vm.provision :ansible do |ansible|
        ansible.limit = "all"
        ansible.playbook = "provisioning/bootstrap.yml"
        ansible.verbose = false
        ansible.compatibility_mode = "2.0"
        ansible.groups = {
            "managers" => ["node-[1:2]"],
            "workers" => ["node-[3:4]"],
          }
        end
      end
    end
  end
end
