Vagrant.configure("2") do |config|
  config.vm.define "ubuntu"
  config.vm.box = "generic/ubuntu2004"
  config.vm.hostname = "ubuntu"
  config.vm.network "private_network", ip: "10.0.0.11"
  config.vm.provider "libvirt" do |v|
    v.memory = "1024"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "deploy.yml"
  end
end
