- name: Check if kudeadm has already run
  stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: output

- name: Init cluster if needed
  shell: kubeadm init --apiserver-advertise-address="{{ hostvars['node-1']['ansible_eth1']['ipv4']['address'] }}" --apiserver-cert-extra-sans="{{ hostvars['node-1']['ansible_eth1']['ipv4']['address'] }}"  --node-name master --pod-network-cidr=192.168.0.0/16
  when: not output.stat.exists
  run_once: yes
  register: ini_cluster

- name: Creates Kubernetes config directory
  when: ini_cluster is succeeded
  file:
    path: ".kube/"
    state: directory

- name: Copy admin.conf
  when: ini_cluster is succeeded
  copy:
    src: "/etc/kubernetes/admin.conf"
    dest: ".kube/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
    remote_src: true


- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

