- name: Manager joins cluster
  shell: "docker swarm join --token {{ hostvars['node-1']['manager_token']['stdout'] }} {{ hostvars['node-1']['ansible_host'] }}:2377 "
  when: swarm_status.rc != 0
  run_once: true
