---
- hosts: all
  become: yes
  tasks:

    - name: Install Docker 
      apt:
        name: docker.io
        state: latest
        update_cache: yes

    - name: Install docker-compose
      apt:
        name: docker-compose
        state: latest
        update_cache: yes

    - name: Install fish
      apt:
        name: fish

    - name: add docker group & change default shell
      user:
        name: vagrant
        groups: docker
        shell: /usr/bin/fish

    - name: ctop -dependencies
      apt_key:
        url: https://azlux.fr/repo.gpg.key

    - name: add ctop repo
      apt_repository:
        repo: deb http://packages.azlux.fr/debian/ stable main

    - name: install ctop
      apt:
        name: docker-ctop
        update_cache: yes

