#!/usr/bin/env ruby
nodes = [

{ :hostname => "ubuntu", :ip => "10.0.0.10", :ram => 1024, :cpus => 1},
{ :hostname => "yeah", :ip => "10.0.0.11", :ram => 1024, :cpus => 1},

]

Vagrant.configure("2") do |config|
  nodes.each do |node|
    config.vm.define node[:hostname] do |conf|
      conf.vm.define node[:hostname]
      conf.vm.box = "generic/ubuntu2004"
      conf.vm.hostname = node[:hostname]
      conf.vm.network "private_network", ip: node[:ip]
      conf.vm.provider "libvirt" do |v|
        v.memory = node[:ram]
        v.cpus = node[:cpus]
      end
    end
  end
  
  config.ssh.insert_key = false
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = false
    ansible.playbook = "deploy.yml"
  end
end
