#!/usr/bin/env ruby

nodes = [
{:hostname => "ubuntu", :ip => "10.0.0.10", :ram => 1024, :cpus => 1},
]

Vagrant.configure("2") do |config|
  nodes.each do |node|
    config.vm.define node[:hostname]
    config.vm.box = "generic/ubuntu2004"
    config.vm.hostname = node[:hostname]
    config.vm.network "private_network", ip: node[:ip]
    config.vm.provider "libvirt" do |v|
      v.memory = node[:ram]
      v.cpus = node[:cpus]
    end
  end
  
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "deploy.yml"
  end
end
